# Base d'aliments française : glucides pour 100 g et portion par défaut.
# Valeurs nutritionnelles indicatives (tables Ciqual simplifiées).

FOODS = [
    # Féculents
    {"id": "riz-blanc-cuit", "name": "Riz blanc cuit", "category": "Féculents", "carbs_per_100g": 26, "portion_g": 150},
    {"id": "riz-complet-cuit", "name": "Riz complet cuit", "category": "Féculents", "carbs_per_100g": 24, "portion_g": 150},
    {"id": "pates-cuites", "name": "Pâtes cuites", "category": "Féculents", "carbs_per_100g": 25, "portion_g": 200},
    {"id": "pommes-de-terre-vapeur", "name": "Pommes de terre vapeur", "category": "Féculents", "carbs_per_100g": 17, "portion_g": 200},
    {"id": "puree-pommes-de-terre", "name": "Purée de pommes de terre", "category": "Féculents", "carbs_per_100g": 14, "portion_g": 200},
    {"id": "frites", "name": "Frites", "category": "Féculents", "carbs_per_100g": 32, "portion_g": 120},
    {"id": "semoule-couscous", "name": "Semoule de couscous cuite", "category": "Féculents", "carbs_per_100g": 23, "portion_g": 200},
    {"id": "quinoa-cuit", "name": "Quinoa cuit", "category": "Féculents", "carbs_per_100g": 18, "portion_g": 150},
    {"id": "boulgour-cuit", "name": "Boulgour cuit", "category": "Féculents", "carbs_per_100g": 19, "portion_g": 150},
    {"id": "mais", "name": "Maïs", "category": "Féculents", "carbs_per_100g": 19, "portion_g": 100},
    {"id": "patate-douce", "name": "Patate douce cuite", "category": "Féculents", "carbs_per_100g": 20, "portion_g": 150},
    {"id": "polenta", "name": "Polenta cuite", "category": "Féculents", "carbs_per_100g": 13, "portion_g": 150},
    {"id": "gnocchis", "name": "Gnocchis", "category": "Féculents", "carbs_per_100g": 22, "portion_g": 200},

    # Boulangerie & céréales
    {"id": "baguette", "name": "Baguette", "category": "Boulangerie", "carbs_per_100g": 55, "portion_g": 100},
    {"id": "pain-de-mie", "name": "Pain de mie", "category": "Boulangerie", "carbs_per_100g": 49, "portion_g": 60},
    {"id": "pain-complet", "name": "Pain complet", "category": "Boulangerie", "carbs_per_100g": 42, "portion_g": 60},
    {"id": "croissant", "name": "Croissant", "category": "Boulangerie", "carbs_per_100g": 42, "portion_g": 60},
    {"id": "pain-au-chocolat", "name": "Pain au chocolat", "category": "Boulangerie", "carbs_per_100g": 47, "portion_g": 70},
    {"id": "brioche", "name": "Brioche", "category": "Boulangerie", "carbs_per_100g": 50, "portion_g": 60},
    {"id": "bagel", "name": "Bagel", "category": "Boulangerie", "carbs_per_100g": 52, "portion_g": 90},
    {"id": "biscottes", "name": "Biscottes", "category": "Boulangerie", "carbs_per_100g": 72, "portion_g": 20},
    {"id": "pain-au-lait", "name": "Pain au lait", "category": "Boulangerie", "carbs_per_100g": 47, "portion_g": 60},
    {"id": "corn-flakes", "name": "Corn flakes", "category": "Boulangerie", "carbs_per_100g": 84, "portion_g": 30},
    {"id": "muesli", "name": "Muesli", "category": "Boulangerie", "carbs_per_100g": 65, "portion_g": 50},
    {"id": "granola", "name": "Granola", "category": "Boulangerie", "carbs_per_100g": 62, "portion_g": 50},

    # Fruits
    {"id": "pomme", "name": "Pomme", "category": "Fruits", "carbs_per_100g": 12, "portion_g": 150},
    {"id": "banane", "name": "Banane", "category": "Fruits", "carbs_per_100g": 20, "portion_g": 120},
    {"id": "orange", "name": "Orange", "category": "Fruits", "carbs_per_100g": 9, "portion_g": 150},
    {"id": "raisin", "name": "Raisin", "category": "Fruits", "carbs_per_100g": 16, "portion_g": 120},
    {"id": "fraises", "name": "Fraises", "category": "Fruits", "carbs_per_100g": 6, "portion_g": 150},
    {"id": "myrtilles", "name": "Myrtilles", "category": "Fruits", "carbs_per_100g": 9, "portion_g": 100},
    {"id": "cerises", "name": "Cerises", "category": "Fruits", "carbs_per_100g": 13, "portion_g": 120},
    {"id": "peche", "name": "Pêche", "category": "Fruits", "carbs_per_100g": 9, "portion_g": 150},
    {"id": "poire", "name": "Poire", "category": "Fruits", "carbs_per_100g": 11, "portion_g": 150},
    {"id": "ananas", "name": "Ananas", "category": "Fruits", "carbs_per_100g": 12, "portion_g": 120},
    {"id": "pasteque", "name": "Pastèque", "category": "Fruits", "carbs_per_100g": 7, "portion_g": 150},
    {"id": "melon", "name": "Melon", "category": "Fruits", "carbs_per_100g": 7, "portion_g": 150},
    {"id": "kiwi", "name": "Kiwi", "category": "Fruits", "carbs_per_100g": 12, "portion_g": 90},
    {"id": "mangue", "name": "Mangue", "category": "Fruits", "carbs_per_100g": 14, "portion_g": 120},
    {"id": "abricot", "name": "Abricots", "category": "Fruits", "carbs_per_100g": 9, "portion_g": 120},
    {"id": "compote-pomme", "name": "Compote de pommes", "category": "Fruits", "carbs_per_100g": 12, "portion_g": 100},
    {"id": "raisins-secs", "name": "Raisins secs", "category": "Fruits", "carbs_per_100g": 65, "portion_g": 30},
    {"id": "dattes", "name": "Dattes", "category": "Fruits", "carbs_per_100g": 68, "portion_g": 30},

    # Légumes
    {"id": "salade-verte", "name": "Salade verte", "category": "Légumes", "carbs_per_100g": 2, "portion_g": 80},
    {"id": "tomate", "name": "Tomate", "category": "Légumes", "carbs_per_100g": 3, "portion_g": 120},
    {"id": "concombre", "name": "Concombre", "category": "Légumes", "carbs_per_100g": 2, "portion_g": 100},
    {"id": "carotte-cuite", "name": "Carotte cuite", "category": "Légumes", "carbs_per_100g": 5, "portion_g": 120},
    {"id": "carotte-rapee", "name": "Carotte râpée", "category": "Légumes", "carbs_per_100g": 7, "portion_g": 80},
    {"id": "brocoli", "name": "Brocoli", "category": "Légumes", "carbs_per_100g": 4, "portion_g": 150},
    {"id": "haricots-verts", "name": "Haricots verts", "category": "Légumes", "carbs_per_100g": 4, "portion_g": 150},
    {"id": "epinards", "name": "Épinards", "category": "Légumes", "carbs_per_100g": 1, "portion_g": 150},
    {"id": "courgette", "name": "Courgette", "category": "Légumes", "carbs_per_100g": 3, "portion_g": 150},
    {"id": "poireau", "name": "Poireau", "category": "Légumes", "carbs_per_100g": 4, "portion_g": 120},
    {"id": "champignons", "name": "Champignons", "category": "Légumes", "carbs_per_100g": 1, "portion_g": 100},
    {"id": "poivron", "name": "Poivron", "category": "Légumes", "carbs_per_100g": 5, "portion_g": 100},
    {"id": "aubergine", "name": "Aubergine", "category": "Légumes", "carbs_per_100g": 3, "portion_g": 120},
    {"id": "soupe-legumes", "name": "Soupe de légumes", "category": "Légumes", "carbs_per_100g": 5, "portion_g": 250},
    {"id": "potiron", "name": "Potiron", "category": "Légumes", "carbs_per_100g": 6, "portion_g": 150},
    {"id": "asperges", "name": "Asperges", "category": "Légumes", "carbs_per_100g": 2, "portion_g": 120},

    # Légumineuses
    {"id": "lentilles-cuites", "name": "Lentilles cuites", "category": "Légumineuses", "carbs_per_100g": 16, "portion_g": 200},
    {"id": "pois-chiches", "name": "Pois chiches cuits", "category": "Légumineuses", "carbs_per_100g": 14, "portion_g": 180},
    {"id": "haricots-blancs", "name": "Haricots blancs cuits", "category": "Légumineuses", "carbs_per_100g": 14, "portion_g": 180},
    {"id": "haricots-rouges", "name": "Haricots rouges cuits", "category": "Légumineuses", "carbs_per_100g": 15, "portion_g": 180},
    {"id": "houmous", "name": "Houmous", "category": "Légumineuses", "carbs_per_100g": 6, "portion_g": 50},

    # Produits laitiers
    {"id": "lait-demi-ecreme", "name": "Lait demi-écrémé", "category": "Produits laitiers", "carbs_per_100g": 5, "portion_g": 200},
    {"id": "yaourt-nature", "name": "Yaourt nature", "category": "Produits laitiers", "carbs_per_100g": 5, "portion_g": 125},
    {"id": "yaourt-fruits", "name": "Yaourt aux fruits", "category": "Produits laitiers", "carbs_per_100g": 12, "portion_g": 125},
    {"id": "fromage-blanc", "name": "Fromage blanc", "category": "Produits laitiers", "carbs_per_100g": 3, "portion_g": 100},
    {"id": "skyr", "name": "Skyr", "category": "Produits laitiers", "carbs_per_100g": 4, "portion_g": 100},
    {"id": "creme-dessert", "name": "Crème dessert", "category": "Produits laitiers", "carbs_per_100g": 15, "portion_g": 100},
    {"id": "glace-vanille", "name": "Glace vanille", "category": "Produits laitiers", "carbs_per_100g": 24, "portion_g": 80},
    {"id": "comte", "name": "Comté", "category": "Produits laitiers", "carbs_per_100g": 0.5, "portion_g": 40},
    {"id": "mozzarella", "name": "Mozzarella", "category": "Produits laitiers", "carbs_per_100g": 1, "portion_g": 60},

    # Viandes & poissons
    {"id": "poulet-grille", "name": "Poulet grillé", "category": "Viandes & poissons", "carbs_per_100g": 0, "portion_g": 150},
    {"id": "steak-boeuf", "name": "Steak de bœuf", "category": "Viandes & poissons", "carbs_per_100g": 0, "portion_g": 150},
    {"id": "saumon", "name": "Saumon", "category": "Viandes & poissons", "carbs_per_100g": 0, "portion_g": 150},
    {"id": "thon", "name": "Thon", "category": "Viandes & poissons", "carbs_per_100g": 0, "portion_g": 100},
    {"id": "oeuf", "name": "Œuf", "category": "Viandes & poissons", "carbs_per_100g": 0.5, "portion_g": 60},
    {"id": "jambon-blanc", "name": "Jambon blanc", "category": "Viandes & poissons", "carbs_per_100g": 0.5, "portion_g": 60},
    {"id": "crevettes", "name": "Crevettes", "category": "Viandes & poissons", "carbs_per_100g": 0, "portion_g": 100},
    {"id": "escalope-dinde", "name": "Escalope de dinde", "category": "Viandes & poissons", "carbs_per_100g": 0, "portion_g": 150},

    # Snacks & sucreries
    {"id": "chocolat-lait", "name": "Chocolat au lait", "category": "Snacks & sucreries", "carbs_per_100g": 59, "portion_g": 30},
    {"id": "chocolat-noir", "name": "Chocolat noir 70%", "category": "Snacks & sucreries", "carbs_per_100g": 33, "portion_g": 30},
    {"id": "cookie", "name": "Cookie", "category": "Snacks & sucreries", "carbs_per_100g": 65, "portion_g": 25},
    {"id": "chips", "name": "Chips", "category": "Snacks & sucreries", "carbs_per_100g": 53, "portion_g": 30},
    {"id": "barre-chocolatee", "name": "Barre chocolatée", "category": "Snacks & sucreries", "carbs_per_100g": 55, "portion_g": 40},
    {"id": "miel", "name": "Miel", "category": "Snacks & sucreries", "carbs_per_100g": 81, "portion_g": 20},
    {"id": "confiture", "name": "Confiture", "category": "Snacks & sucreries", "carbs_per_100g": 60, "portion_g": 30},
    {"id": "sucre", "name": "Sucre (1 morceau)", "category": "Snacks & sucreries", "carbs_per_100g": 100, "portion_g": 6},
    {"id": "pate-a-tartiner", "name": "Pâte à tartiner", "category": "Snacks & sucreries", "carbs_per_100g": 57, "portion_g": 20},
    {"id": "pain-epices", "name": "Pain d'épices", "category": "Snacks & sucreries", "carbs_per_100g": 65, "portion_g": 30},
    {"id": "madeleine", "name": "Madeleine", "category": "Snacks & sucreries", "carbs_per_100g": 62, "portion_g": 30},
    {"id": "gaufre", "name": "Gaufre", "category": "Snacks & sucreries", "carbs_per_100g": 38, "portion_g": 80},
    {"id": "crepe", "name": "Crêpe", "category": "Snacks & sucreries", "carbs_per_100g": 30, "portion_g": 100},
    {"id": "tarte-pommes", "name": "Tarte aux pommes", "category": "Snacks & sucreries", "carbs_per_100g": 30, "portion_g": 120},

    # Boissons
    {"id": "jus-orange", "name": "Jus d'orange", "category": "Boissons", "carbs_per_100g": 9, "portion_g": 200},
    {"id": "cola", "name": "Cola", "category": "Boissons", "carbs_per_100g": 11, "portion_g": 330},
    {"id": "cola-light", "name": "Cola light", "category": "Boissons", "carbs_per_100g": 0, "portion_g": 330},
    {"id": "lait-chocolate", "name": "Lait chocolaté", "category": "Boissons", "carbs_per_100g": 9, "portion_g": 250},
    {"id": "biere", "name": "Bière", "category": "Boissons", "carbs_per_100g": 3, "portion_g": 250},
    {"id": "sirop-dilue", "name": "Sirop dilué", "category": "Boissons", "carbs_per_100g": 10, "portion_g": 200},
    {"id": "smoothie", "name": "Smoothie fruits", "category": "Boissons", "carbs_per_100g": 12, "portion_g": 200},
    {"id": "eau", "name": "Eau", "category": "Boissons", "carbs_per_100g": 0, "portion_g": 250},
    {"id": "cafe-noir", "name": "Café sans sucre", "category": "Boissons", "carbs_per_100g": 0, "portion_g": 100},
    {"id": "the-nature", "name": "Thé sans sucre", "category": "Boissons", "carbs_per_100g": 0, "portion_g": 200},

    # Plats préparés
    {"id": "pizza-margherita", "name": "Pizza margherita", "category": "Plats préparés", "carbs_per_100g": 30, "portion_g": 300},
    {"id": "sandwich-jambon-beurre", "name": "Sandwich jambon-beurre", "category": "Plats préparés", "carbs_per_100g": 36, "portion_g": 200},
    {"id": "quiche-lorraine", "name": "Quiche lorraine", "category": "Plats préparés", "carbs_per_100g": 24, "portion_g": 150},
    {"id": "croque-monsieur", "name": "Croque-monsieur", "category": "Plats préparés", "carbs_per_100g": 30, "portion_g": 200},
    {"id": "burger", "name": "Burger", "category": "Plats préparés", "carbs_per_100g": 30, "portion_g": 220},
    {"id": "sushis", "name": "Sushis", "category": "Plats préparés", "carbs_per_100g": 25, "portion_g": 150},
    {"id": "pates-carbonara", "name": "Pâtes carbonara", "category": "Plats préparés", "carbs_per_100g": 20, "portion_g": 300},
    {"id": "couscous-legumes", "name": "Couscous aux légumes", "category": "Plats préparés", "carbs_per_100g": 18, "portion_g": 350},
    {"id": "paella", "name": "Paella", "category": "Plats préparés", "carbs_per_100g": 18, "portion_g": 300},
    {"id": "chili-con-carne", "name": "Chili con carne", "category": "Plats préparés", "carbs_per_100g": 10, "portion_g": 300},
    {"id": "lasagnes", "name": "Lasagnes", "category": "Plats préparés", "carbs_per_100g": 16, "portion_g": 300},
    {"id": "gratin-dauphinois", "name": "Gratin dauphinois", "category": "Plats préparés", "carbs_per_100g": 12, "portion_g": 250},
    {"id": "risotto", "name": "Risotto aux champignons", "category": "Plats préparés", "carbs_per_100g": 20, "portion_g": 300},
    {"id": "omelette", "name": "Omelette", "category": "Plats préparés", "carbs_per_100g": 1, "portion_g": 150},
    {"id": "salade-cesar", "name": "Salade César", "category": "Plats préparés", "carbs_per_100g": 5, "portion_g": 300},
    {"id": "kebab", "name": "Kebab", "category": "Plats préparés", "carbs_per_100g": 32, "portion_g": 300},
]
